### ISSUE TITLE
where to find configuration documentation

### ISSUE THREAD

**Issue by edzob** [bvignau/SLRIA#2]
Just discovered SLRIA.
Aim is to extract from one PDF the references (43). 
Paper has no DOI.

Where can I find documentation on the config file, esp. the request section?

Thanks!

`[Request]
r0 = "Personal Identification with PPG"
r1 = "Personal recognition with PPG"
r2 = "Signature with PPG"
r3 = "biometric identification with photoplethysmography"
r4 = "Personal Identification with photoplethysmography"`

**Comment by bvignau** [comment]
Hello, 

The request section is only here to help you organize the folder of your SLR. You simply enter all the requests you want to make to your search engine. If you only want to extract the references of one paper, SLRIA may not be appropriate. It is designed to extract, filter and merge all the references of several papers at the same time. If you really want to use this software to extract the references of one paper, just keep the request r0 and use any phrase you want to organize (like "paperXXX"). It will create a folder with that name and then follow the rest of the instructions in the readme file.

Have a nice day.

**Comment by edzob** [comment]
Thank you very much for the quick answer. I will try to understand the tool.
